services:
  web:
    build: .
    container_name: seo-analyzer-web
    image: seo-analyzer-web:1.0
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.env
    command: npm run dev
    networks:
      - seo-analyzer-network
    develop:
      watch:
        - action: sync
          path: ./
          initial_sync: true
          target: /app
          ignore:
            - node_modules
            - .next
networks:
  seo-analyzer-network:
    external: true
